baseurl: "/manual"
url: "https://kiksworks.github.io"

collections:
  education-board:
   output: true
  management:
    output: true
  circuit:
    output: true
  control:
    output: true
  robot-problem:
    output: true
  assembly:
    output: true    
  